on:
  pull_request_target:
    paths-ignore:
      - ".github/workflows/**"

  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check_job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' || github.event.pull_request.merged }}
    steps:
    - name: echo env
      run: |
        echo ${{ github.event.pull_request }}
        echo "GITHUB_ENENT_NAME: $GITHUB_EVENT_NAME"
        echo ${{ github.event.pull_request }}

